### ISSUE TITLE
Issue with CSIDriver API used

### ISSUE THREAD

**Issue by tonyjames** [nutanix/openshift#1] opened 2021-08-01 19:25 UTC
As of Kubernetes 1.18 the CSIDriver object has reached GA status [1] and the API used should be "v1" instead of "v1beta1". This is causing a warning to display in my OpenShift cluster.

[1] https://kubernetes-csi.github.io/docs/csi-driver-object.html

<img width="542" alt="Screen Shot 2021-08-01 at 3 24 35 PM" src="https://user-images.githubusercontent.com/3128081/127782984-96c56f2e-efdf-4188-b518-0dd27ac6db2f.png">

**Comment by vnephologist** [comment] 2021-08-01 23:11
Thanks for raising @tonyjames. This probably need to be fixed across other CSI doc too. I’ll test, but assuming you’ve had no issue using v1?

cc: @tuxtof

**Comment by vnephologist** [comment] 2021-08-01 23:17
@tonyjames I just did a scan of doc and don’t see any reference to v1beta1. I wonder where it snuck into your install. Did you use the Operator?

**Comment by JonKohler** [comment] 2021-08-02 00:04
I (believe) I found the problem in the private repo where the CSI code for RH lives. We gotta open that up repo-wise, but @tuxtof ... I think the problem is here: helm-charts/nutanix-csi-storage/templates/csi-driver.yaml

Can you check it out?

**Comment by tonyjames** [comment] 2021-08-02 00:16
@JonKohler I found this as well: https://github.com/nutanix/csi-plugin/blob/master/deploy/csi-driver.yaml

I'm using version 0.1.3 of the Nutanix CSI operator with my OpenShift environment. It seems to be working just fine. This error is cosmetic but may become an issue in a future version of OpenShift when the v1beta1 version of csidrivers is removed.

**Comment by JonKohler** [comment] 2021-08-02 00:26
Yep we'd need to fix it in both places I believe and also make sure for the generic csi driver that we don't have any issues for other consumers (Eg karbon)

**Comment by tuxtof** [comment] 2021-08-02 06:18
@tonyjames @JonKohler @vnephologist 
it is only a warning without impact on the operation but it is already under control and planned to be fixed in a futur version.

All manifest is managed commonly for Karbon, raw CSI and operator inherits it. So we will change it first at the source

**Comment by tuxtof** [comment] 2022-03-29 13:39
fixed in recent CSI operator

**Closed as completed by tuxtof** 2022-03-29 13:39 UTC
